site_name: 速致文档中心
repo_url: https://github.com/GridSafe/suzhi-help
pages:
- 首页: index.md

- 关于速致:
    - 速致服务: suzhi/service.md

- 使用速致:
    - 常见问题:
        - 为什么要使用 CDN: common/why-cdn.md
        - 怎样用好 CDN: common/how-to-use.md
        - CDN 常见服务: common/cdn-serve.md
    - 登录和注册: user-guide/signup-and-login.md
    - 修改密码: user-guide/update-passwd.md
    - 找回密码: user-guide/reset-passwd.md
    - 添加域名: user-guide/add-domain.md
    - 添加子域名: user-guide/add-sub-domain.md
    - 域名接入（验证/指向）: user-guide/domain-handle.md
    - 安全链接 : user-guide/secure_link.md
    - 图片处理: user-guide/img.md
    - HLS 直播分发: user-guide/hls.md
    - RTMP 直播分发: user-guide/rtmp.md
    - 云转码处理: user-guide/transcode.md

- 开发者资源:
    - 云分发 API 文档: dev/api-v3.md
    - 视频转码 API 文档(旧版): dev/avapi.md
    - 视频转码 API 文档(新版): dev/videoapi.md
    - 直播 API 文档: dev/liveapi.md
    - 旧版 API 文档: dev/api-docs.md

- 运维分享:
    - 判断域名是否已经使用速致云: share/judge.md
    - 谨慎设置防火墙以免拦截回源: share/firewall.md
    - 过期时间控制: share/expired.md
    - 获取用户访问的原始 IP: share/origin_ip.md
    - 源站状态检测: share/source.md

- 产品课堂:
    - 云分发: product/cdn.md


# theme: flatly
theme_dir: 'theme'
